CREATE TABLE `tb_main_bbs` (
	`no` INT(11) NOT NULL AUTO_INCREMENT COMMENT '번호',
	`title` VARCHAR(300) NULL DEFAULT NULL COMMENT '제목',
	`content` TEXT NULL DEFAULT NULL COMMENT '내용',
	`reg_id` VARCHAR(100) NULL DEFAULT NULL COMMENT '작성자_ID',
	`reg_dt` DATETIME NOT NULL DEFAULT '',
	`del_yn` VARCHAR(10) NOT NULL DEFAULT 'N' COMMENT '사용여부',
	`mod_id` VARCHAR(100) NULL DEFAULT NULL COMMENT '수정자_ID',
	`mod_dt` TIMESTAMP NULL DEFAULT '',
	PRIMARY KEY (`no`)
)
COMMENT='메인 게시판 테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=73
;
